#---------------------------------# 
#      environment configuration  # 
#---------------------------------# 
version: 2.3.{build}
os: WMF 5
install:
  - ps: . .\AppVeyor\AppVeyorInstall.ps1

environment:
  NuGetApiKey:
    secure: pGoVS0WAc1L+bMaszhUU8nBkdz0TFLiFNgE+jCYi9TnviTi+JhBDvsKeXMZZMnOl
#  MyNonSecureVar: NonSecure

  ModuleName: NewLabEnvironment
#---------------------------------# 
#      build configuration        # 
#---------------------------------# 
build_script: 
  - ps: . .\AppVeyor\AppVeyorBuild.ps1

#---------------------------------# 
#      test configuration         # 
#---------------------------------# 
test_script: 
  - ps: . .\AppVeyor\AppVeyorTest.ps1

#---------------------------------# 
#      deployment configuration   # 
#---------------------------------# 
deploy_script: 
  - ps: . .\AppVeyor\AppveyorDeploy.ps1