#---------------------------------# 
#      environment configuration  # 
#---------------------------------# 
version: 2.4.{build}
pull_requests:
  do_not_increment_build_number: true
skip_branch_with_pr: true
image: WMF 5
build:
  verbosity: normal

only_commits:
  message: /build/

install:
  - ps: . .\AppVeyor\AppVeyorInstall.ps1

environment:
  NuGetApiKey:
    secure: pGoVS0WAc1L+bMaszhUU8nBkdz0TFLiFNgE+jCYi9TnviTi+JhBDvsKeXMZZMnOl
#  MyNonSecureVar: NonSecure

  ModuleName: NewLabEnvironment
  
#---------------------------------# 
#      build configuration        # 
#---------------------------------# 
build_script: 
  - ps: . .\AppVeyor\AppVeyorBuild.ps1

#---------------------------------# 
#      test configuration         # 
#---------------------------------# 
test_script: 
  - ps: . .\AppVeyor\AppVeyorTest.ps1

#---------------------------------# 
#      deployment configuration   # 
#---------------------------------# 
deploy_script: 
  - ps: . .\AppVeyor\AppveyorDeploy.ps1